"""
Output Agent — turns the negotiated mess into something a team can actually use.

Takes the agreed-upon backlog and formats it as clean markdown: stories with
estimates, acceptance criteria, test requirements, and anything flagged for
the next sprint. The goal is something you can paste straight into Jira or Linear.
"""

import json

from agents.foundry_client import FoundryClient

SYSTEM_PROMPT = """You are a technical writer producing sprint documentation.
Format the provided sprint plan as a professional markdown document.
Be specific and actionable — this document will be handed directly to a development team to execute.
Return markdown only. No explanation. No code fences."""


class OutputAgent:
    def __init__(self):
        self.client = FoundryClient()

    def run(self, negotiated: dict, sprint_context: dict) -> str:
        sprint = negotiated.get("sprint_number", sprint_context.get("sprint", 1))
        project_name = sprint_context.get("project_name", "Project")

        # ask the LLM to write the narrative context sections
        user_prompt = (
            "Format this sprint plan as professional markdown. "
            "Write an executive summary, a brief section on what was negotiated and why, "
            "and any implementation guidance for the team. "
            "Do NOT include tables — those will be added separately.\n\n"
            + json.dumps(negotiated, indent=2)
        )
        narrative = self.client.chat(SYSTEM_PROMPT, user_prompt).strip()

        # --- programmatically built sections (reliable structure) ---

        header = (
            f"## Sprint {sprint} Backlog — {project_name}\n"
            f"> Generated by PRD-to-Sprint Negotiator\n"
        )

        goal_section = f"## Sprint Goal\n{negotiated.get('sprint_goal', '')}\n"

        # committed scope table
        total_pts = negotiated.get("total_committed_points", 0)
        capacity = negotiated.get("effective_capacity", 40)
        scope_rows = "\n".join(
            f"| {f['feature_name']} | {f['story_points']} | "
            + ("; ".join(f["qa_requirements"][:2]) if f.get("qa_requirements") else "—")
            + " |"
            for f in negotiated.get("included_features", [])
        )
        scope_section = (
            f"## Committed Scope ({total_pts} / {capacity} pts)\n"
            f"| Feature | Story Points | QA Requirements |\n"
            f"|---------|-------------|------------------|\n"
            f"{scope_rows}\n"
        )

        # excluded table
        excluded = negotiated.get("excluded_features", [])
        excluded_section = ""
        if excluded:
            excluded_rows = "\n".join(
                f"| {f['feature_name']} | {f['reason_excluded']} | {f.get('recommended_sprint', '—')} |"
                for f in excluded
            )
            excluded_section = (
                f"## Excluded This Sprint\n"
                f"| Feature | Reason | Planned For |\n"
                f"|---------|--------|-------------|\n"
                f"{excluded_rows}\n"
            )

        # negotiation notes
        notes = negotiated.get("negotiation_notes", [])
        notes_section = ""
        if notes:
            notes_section = "## Negotiation Notes\n" + "\n".join(f"- {n}" for n in notes) + "\n"

        # risks
        risks = negotiated.get("risks", [])
        risks_section = ""
        if risks:
            risks_section = "## Risks\n" + "\n".join(f"- {r}" for r in risks) + "\n"

        # QA checklist — one block per included feature, always present
        qa_blocks = []
        for f in negotiated.get("included_features", []):
            reqs = f.get("qa_requirements", [])
            if reqs:
                checks = "\n".join(f"- [ ] {r}" for r in reqs)
            else:
                checks = "- [ ] Define and agree on QA requirements before development starts"
            qa_blocks.append(f"### {f['feature_name']}\n{checks}")
        qa_section = "## QA Checklist\n" + "\n\n".join(qa_blocks) + "\n" if qa_blocks else "## QA Checklist\n_No features committed this sprint._\n"

        # carried over from last sprint
        carried = negotiated.get("carried_over", [])
        carried_section = ""
        if sprint > 1 and carried:
            items = "\n".join(f"- {item}" for item in carried)
            carried_section = f"## Carried Over from Sprint {sprint - 1}\n{items}\n"

        # assemble the full document
        sections = [
            header,
            narrative,
            goal_section,
            scope_section,
        ]
        if excluded_section:
            sections.append(excluded_section)
        if notes_section:
            sections.append(notes_section)
        if risks_section:
            sections.append(risks_section)
        if qa_section:
            sections.append(qa_section)
        if carried_section:
            sections.append(carried_section)

        return "\n\n".join(sections)
