"""
Output Agent — turns the negotiated mess into something a team can actually use.

Takes the agreed-upon backlog and formats it as clean markdown: stories with
estimates, acceptance criteria, test requirements, and anything flagged for
the next sprint. The goal is something you can paste straight into Jira or Linear.
"""

import json

from agents.foundry_client import FoundryClient

SYSTEM_PROMPT = """You are a technical writer producing sprint documentation.
Format the provided sprint plan as a professional markdown document.
Be specific and actionable — this document will be handed directly to a development team to execute.
Write like a senior developer documenting for their own team.
No corporate filler phrases. No sentences like 'this prioritization comes with acknowledged risks'.
Be direct and specific. If something was excluded, say why in plain English.
If a feature has risks, name them specifically.
Return markdown only. No explanation. No code fences."""


class OutputAgent:
    def __init__(self):
        self.client = FoundryClient()

    def run(
        self,
        negotiated: dict,
        sprint_context: dict,
        qa_output: dict = None,
        engineer_output: dict = None,
    ) -> str:
        sprint = negotiated.get("sprint_number", sprint_context.get("sprint", 1))
        project_name = sprint_context.get("project_name", "Project")

        # build lookup maps from optional upstream outputs
        qa_map = {}
        if qa_output:
            for item in qa_output.get("qa_review", []):
                qa_map[item["feature_id"]] = item

        eng_map = {}
        if engineer_output:
            for est in engineer_output.get("estimates", []):
                eng_map[est["feature_id"]] = est

        # LLM writes the narrative sections only
        user_prompt = (
            "Write an executive summary and negotiation context for this sprint plan. "
            "Say what's in the sprint and why the excluded features didn't make it. "
            "Do NOT include tables — those will be added separately.\n\n"
            + json.dumps(negotiated, indent=2)
        )
        narrative = self.client.chat(SYSTEM_PROMPT, user_prompt).strip()

        # --- programmatically built sections ---

        header = (
            f"## Sprint {sprint} Backlog — {project_name}\n"
            f"> Generated by PRD-to-Sprint Negotiator\n"
        )

        goal_section = f"## Sprint Goal\n{negotiated.get('sprint_goal', '')}\n"

        # committed scope table — story points locked to Engineer Agent values
        total_pts = negotiated.get("total_committed_points", 0)
        capacity = negotiated.get("effective_capacity", 40)
        scope_rows = []
        for f in negotiated.get("included_features", []):
            pts = eng_map.get(f["feature_id"], {}).get("story_points") or f["story_points"]
            qa_item = qa_map.get(f["feature_id"], {})
            qa_summary = "; ".join((qa_item.get("test_cases") or [])[:2]) or "—"
            scope_rows.append(f"| {f['feature_name']} | {pts} | {qa_summary} |")

        scope_section = (
            f"## Committed Scope ({total_pts} / {capacity} pts)\n"
            f"| Feature | Story Points | QA Requirements |\n"
            f"|---------|-------------|------------------|\n"
            + "\n".join(scope_rows) + "\n"
        )

        # excluded table
        excluded = negotiated.get("excluded_features", [])
        excluded_section = ""
        if excluded:
            excluded_rows = "\n".join(
                f"| {f['feature_name']} | {f['reason_excluded']} | {f.get('recommended_sprint', '—')} |"
                for f in excluded
            )
            excluded_section = (
                f"## Excluded This Sprint\n"
                f"| Feature | Reason | Planned For |\n"
                f"|---------|--------|-------------|\n"
                f"{excluded_rows}\n"
            )

        # negotiation notes
        notes = negotiated.get("negotiation_notes", [])
        notes_section = ""
        if notes:
            notes_section = "## Negotiation Notes\n" + "\n".join(f"- {n}" for n in notes) + "\n"

        # risks
        risks = negotiated.get("risks", [])
        risks_section = ""
        if risks:
            risks_section = "## Risks\n" + "\n".join(f"- {r}" for r in risks) + "\n"

        # QA checklist — raw test_cases + edge_cases from QA Agent when available
        qa_blocks = []
        for f in negotiated.get("included_features", []):
            qa_item = qa_map.get(f["feature_id"])
            if qa_item:
                test_cases = qa_item.get("test_cases", [])
                edge_cases = qa_item.get("edge_cases", [])
                checks = "\n".join(f"- [ ] {tc}" for tc in test_cases)
                if edge_cases:
                    checks += "\n" + "\n".join(f"- [ ] Edge: {ec}" for ec in edge_cases)
            else:
                # fallback: summary qa_requirements from negotiated output
                reqs = f.get("qa_requirements", [])
                checks = (
                    "\n".join(f"- [ ] {r}" for r in reqs)
                    if reqs
                    else "- [ ] Define and agree on QA requirements before development starts"
                )
            qa_blocks.append(f"### {f['feature_name']}\n{checks}")

        qa_section = (
            "## QA Checklist\n" + "\n\n".join(qa_blocks) + "\n"
            if qa_blocks
            else "## QA Checklist\n_No features committed this sprint._\n"
        )

        # carried over from last sprint
        carried = negotiated.get("carried_over", [])
        carried_section = ""
        if sprint > 1 and carried:
            items = "\n".join(f"- {item}" for item in carried)
            carried_section = f"## Carried Over from Sprint {sprint - 1}\n{items}\n"

        sections = [header, narrative, goal_section, scope_section]
        if excluded_section:
            sections.append(excluded_section)
        if notes_section:
            sections.append(notes_section)
        if risks_section:
            sections.append(risks_section)
        if qa_section:
            sections.append(qa_section)
        if carried_section:
            sections.append(carried_section)

        return "\n\n".join(sections)
